### ISSUE TITLE
CIT texture packs can't be selected

### ISSUE THREAD

**Issue by Agent00Ming** [QuantumFusionMC/DashLoader-Definitions#17]
**Describe the bug**
All selected texture packs are removed when attempting to load a resource pack using CITs.

**To Reproduce**
1. Select a CIT resource pack
2. Click 'done'
3. Loading screen flickers and all selected resource packs are removed

**Expected behavior**
Resource pack using CITs load as would a resource pack without CITs

**Context (please complete the following information):**
 - CIT Resewn 1.1.0
 - DashLoader Version 4.0.0
 - Fabric API 0.55.3
 - Minecraft Version 1.19

**Additional context**
CIT resource packs can occasionally be selected during play but always fail when starting Minecraft.

**Comment by Agent00Ming** [comment]
[11:13:01] [Worker-Main-18/INFO]: [citresewn] Loading item CIT models...
[11:13:01] [Worker-Main-18/INFO]: Injecting 22701 Cached Models
[11:13:01] [Worker-Main-18/INFO]: Loaded 0 unsupported models.
[11:13:01] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Circular reference while loading minecraft:item/generated
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalStateException: Circular reference while loading minecraft:item/generated
	at net.minecraft.class_1088.method_4726(class_1088.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_793.method_4754(class_793.java:161) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_4732(class_1088.java:215) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Object2ObjectOpenHashMap.java:1195) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Object2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapSpliterator.forEachRemaining(Object2ObjectOpenHashMap.java:857) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.forEachRemaining(Object2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_1088.<init>(class_1088.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18178(class_1092.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18789(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more

**Comment by Agent00Ming** [comment]
~~This issue doesn't occur anymore when using 'CIT Resewn' 1.1.1 on Minecraft 1.19.~~
Issue is still present. View issue #20 comments.
