### ISSUE TITLE
Crash with Xaero's minimap mod

### ISSUE THREAD

**Issue by AnomalousDeity** [QuantumFusionMC/DashLoader-Definitions#24]
**Describe the bug**
The game will crash on world loading in or after some time of exploring with Xaero's minimap and Dashloader
Xaero is aware of this and closes reports saying its dashloader, it prevents my mod from loading its resources 

**To Reproduce**
1. load into a world with Xaero's Minimap mod and Dashloader
2. Play the game for 30 minutes to a hour of exploring Or Restart mc and load back into the world
3. Black screen or Jumping from loading world to Saving world screen
4. game crashes with a 50/50% to pop up the error, but always makes the crash report in .minecraft/crash-report directory 

**Expected behavior**
fast loading of 227 mods for a upcoming multiplayer server (which this mod does amazingly 10/10 would use all the time) and not crashing on loading in, or after 30 mins to a hour of standing around or exploring

**Screenshots**

**Context (please complete the following information):**
 - DashLoader Version 4.0.0
 - Minecraft Version 1.19
 -Modloader Fabric 
 -Modloader version 0.14.8

**Full Logs**
https://pastebin.com/txQhdNRZ
(I dont know which of my specified dated Logs to post since they are in .gz format and it comes out in Giberish when I try to look at them) but ill add my latest log if it helps any)

**Additional context**
Works fine if I remove the minimap mod or dashloader but together after some time or on loading in just crashes to desktop
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/9173161/latest.log)

**Comment by PweSol** [comment]
I'm running DashLoader and Xaero's mods together just fine.

**Comment by pewblaze** [comment]
Ive got the same problem. It works a few (random) times together and not sure why but after a while it crashes instantantly. 
Mabye my log helps? ^^" Xaero said its a dashloader issue.
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/875

My crash log:
https://gist.github.com/pewblaze/28b3b428352ba6ebfaa1513d8f2cac20

My latest log:
https://gist.github.com/pewblaze/fe13cabf09aa45189e0d6eaf4181305b

**Comment by thexaero** [comment]
Dashloader seems incompatible with Custom Entity Models / Optifine resource packs. The error during resource loading stops resource reload listeners from being called, which can cause other mods to crash, e.g. my mods.

**Comment by alphaqu** [comment]
Hi, i get this in my dev env
```
Caused by: java.lang.NoSuchFieldException: shader
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at xaero.common.misc.Misc.getFieldReflection(Misc.java:188) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	at xaero.common.misc.Misc.getFieldReflection(Misc.java:177) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	at xaero.common.minimap.render.radar.EntityIconPrerenderer.<init>(EntityIconPrerenderer.java:217) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	at xaero.common.minimap.render.MinimapFBORenderer.loadFrameBuffer(MinimapFBORenderer.java:77) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	at xaero.common.minimap.MinimapProcessor.checkFBO(MinimapProcessor.java:130) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	at xaero.common.minimap.MinimapInterfaceInstance.prePotentialRender(MinimapInterfaceInstance.java:33) ~[xaerominimap-22.17.0-64b5720b4b825f21.jar:?]
	... 14 more
```

But, its really hard to debug this issue without the source code of the original mod as its closed source. @thexaero are you able to help/provide me with the source code so i can find the conflict.
