### ISSUE TITLE
Compatibility issues with Better End/Nether

### ISSUE THREAD

**Issue by 1GladCat** [QuantumFusionMC/DashLoader-Definitions#55]
**Describe the bug**
When booting up with Better End/Nether + Dashloader installed, Dashloader says "there is an internal error".

**To Reproduce**
1. Dowload the mods listed below and install Minecraft Version [1.19.3] and Fabric Version [0.14.14]
fabric-api-0.73.0+1.19.3
dashloader-5.0.0-alpha.9+1.19.3
better-nether-8.1.3
better-end-3.1.2
bclib-2.2.4

2. Launch the game.

**Expected behavior**
It will say "there is an internal error". If you remove Better End/Nether it will work as expected. 

**Screenshots**
![billede](https://user-images.githubusercontent.com/63114970/218514345-b0e612d1-ba1e-40b4-a5a8-bd64cef8cf55.png)

**Logs**
[17:25:07] [Render thread/INFO]: Minecraft reloaded in 3.4s
[17:25:07] [Render thread/INFO]: en_us
[17:25:07] [Render thread/INFO]: Found translations
[17:25:07] [dashloader-thread/INFO]: Starting DashLoader Caching
[17:25:07] [dashloader-thread/INFO]: Checking for cache count.
[17:25:07] [dashloader-thread/ERROR]: Could not enforce maximum cache 
java.nio.file.NoSuchFileException: .\dashloader-cache\client\68A090049DD3DCA999711CA86A9F5F90
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535) ~[?:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:482) ~[?:?]
	at java.nio.file.Files.list(Files.java:3792) ~[?:?]
	at dev.notalpha.dashloader.Cache.save(Cache.java:78) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at net.minecraft.class_425.md3c1472$lambda$done$1$0(class_425.java:576) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:25:07] [dashloader-thread/ERROR]: Failed caching
java.lang.RuntimeException: Could not create DashObject class_1095
	at dev.notalpha.dashloader.registry.FactoryBinding.create(FactoryBinding.java:44) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.data.ChunkFactory.create(ChunkFactory.java:31) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.lambda$add$0(RegistryFactory.java:73) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.create(RegistryWriter.java:33) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.add(RegistryFactory.java:72) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.lambda$save$0(ModelModule.java:57) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.quantumfusion.taski.builtin.StepTask.lambda$doForEach$1(StepTask.java:143) ~[dev_quantumfusion_taski-2.1.0-96b67398e178a8d3.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at dev.quantumfusion.taski.builtin.StepTask.doForEach(StepTask.java:142) ~[dev_quantumfusion_taski-2.1.0-96b67398e178a8d3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.save(ModelModule.java:54) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.ModelModule.save(ModelModule.java:30) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.io.MappingSerializer.save(MappingSerializer.java:48) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.Cache.save(Cache.java:128) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at net.minecraft.class_425.md3c1472$lambda$done$1$0(class_425.java:576) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: someone is having fun with lambda selectors again
	at dev.notalpha.dashloader.client.DashLoaderClient.lambda$onDashLoaderSave$1(DashLoaderClient.java:111) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.lambda$add$1(RegistryFactory.java:84) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.create(RegistryWriter.java:33) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryFactory.add(RegistryFactory.java:83) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.RegistryWriter.add(RegistryWriter.java:26) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.client.model.DashMultipartBakedModel.<init>(DashMultipartBakedModel.java:48) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.FactoryBinding$InvokeType.lambda$static$0(FactoryBinding.java:72) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	at dev.notalpha.dashloader.registry.FactoryBinding.create(FactoryBinding.java:42) ~[dashloader-5.0.0-alpha.9+1.19.3.jar:?]
	... 14 more
[17:25:07] [dashloader-thread/INFO]: [46m[30m DashLoader Status change IDLE
[0m
[17:27:01] [Render thread/INFO]: Stopping!
Processen sluttede med kode 0.

**Comment by alphaqu** [comment]
Hi, this has been a long time incompatibility and its their end. Have a nice day!
