### ISSUE TITLE
[LAUNCH]: Crash on Quilt.

### ISSUE THREAD

**Issue by MagmaSlime123** [QuantumFusionMC/DashLoader-Definitions#73]
### Version

dashloader-5.0.0-beta.1+1.20.0

### Minecraft Version

1.20.1.

### Entire Logs

https://mclo.gs/2i2eiZP

### Additional Notes

Quilt mentioned this was Sodium's doing, but Sodium's dev says this is DashLoaders fault? I'm not sure who to report this to at this point.

**Comment by BuggyAl** [comment]
Can confirm, but it appears to happen randomly. I assume Sodium uses some part of the Dashloader cache that isn't instantiated. 
Stack trace with MixinTrace mod installed:
```
 ---- Minecraft Crash Report ----
 // Daisy, daisy...
 
 Time: 2023-08-08 18:19:50
 Description: Rendering overlay
 
 java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
 	at net.minecraft.class_5944.redirect$znc000$sodium$redirectGetUniformLocation(class_5944.java:1667)
 	at net.minecraft.class_5944.method_34586(class_5944.java:392)
 	at net.minecraft.class_291.method_34431(class_291.java:180)
 	at net.minecraft.class_291.method_34427(class_291.java:123)
 	at net.minecraft.class_286.method_43438(class_286.java:33)
 	at net.minecraft.class_286.method_43433(class_286.java:26)
 	at net.minecraft.class_332.method_25295(class_332.java:398)
 	at net.minecraft.class_332.method_25297(class_332.java:378)
 	at net.minecraft.class_332.method_25293(class_332.java:362)
 	at net.minecraft.class_425.method_25394(class_425.java:124)
 	at net.minecraft.class_757.method_3192(class_757.java:934)
 	at net.minecraft.class_310.method_1523(class_310.java:1219)
 	at net.minecraft.class_310.method_1514(class_310.java:802)
 	at net.minecraft.client.main.Main.main(Main.java:250)
 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
 
 
 A detailed walkthrough of the error, its code path and all known details is as follows:
 ---------------------------------------------------------------------------------------
 
 -- Head --
 Thread: Render thread
 Stacktrace:
 	at net.minecraft.class_5944.redirect$znc000$sodium$redirectGetUniformLocation(class_5944.java:1667)
 	at net.minecraft.class_5944.method_34586(class_5944.java:392)
 	at net.minecraft.class_291.method_34431(class_291.java:180)
 	at net.minecraft.class_291.method_34427(class_291.java:123)
 	at net.minecraft.class_286.method_43438(class_286.java:33)
 	at net.minecraft.class_286.method_43433(class_286.java:26)
 	at net.minecraft.class_332.method_25295(class_332.java:398)
 	at net.minecraft.class_332.method_25297(class_332.java:378)
 	at net.minecraft.class_332.method_25293(class_332.java:362)
 	at net.minecraft.class_425.method_25394(class_425.java:124)
 Mixins in Stacktrace:
 	net.minecraft.class_5944:
 		dev.notalpha.dashloader.mixin.accessor.ShaderProgramAccessor (dashloader.mixins.json)
 		me.jellysquid.mods.sodium.mixin.features.shader.uniform.ShaderProgramMixin (sodium.mixins.json)
 		net.fabricmc.fabric.mixin.client.rendering.shader.ShaderProgramMixin (fabric-rendering-v1.mixins.json)
 	net.minecraft.class_332:
 		me.jellysquid.mods.sodium.mixin.features.textures.animations.tracking.DrawableHelperMixin (sodium.mixins.json)
 	net.minecraft.class_425:
 		dev.notalpha.dashloader.mixin.main.SplashScreenMixin (dashloader.mixins.json)
 
 -- Overlay render details --
 Details:
 	Overlay name: net.minecraft.class_425
 Stacktrace:
 	at net.minecraft.class_757.method_3192(class_757.java:934)
 	at net.minecraft.class_310.method_1523(class_310.java:1219)
 	at net.minecraft.class_310.method_1514(class_310.java:802)
 	at net.minecraft.client.main.Main.main(Main.java:250)
 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
 Mixins in Stacktrace:
 	net.minecraft.class_757:
 		me.jellysquid.mods.sodium.mixin.features.gui.hooks.console.GameRendererMixin (sodium.mixins.json)
 		net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)
 		dev.notalpha.dashloader.mixin.option.cache.shader.GameRendererMixin (dashloader.mixins.json)
 		net.fabricmc.fabric.mixin.client.rendering.shader.GameRendererMixin (fabric-rendering-v1.mixins.json)
 	net.minecraft.class_310:
 		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
 		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
 		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
 		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
 		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
 		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (dashloader.mixins.json)
 		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
 		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
 	net.minecraft.client.main.Main:
 		dev.notalpha.dashloader.mixin.main.MainMixin (dashloader.mixins.json)
 
 -- Last reload --
 Details:
 	Reload number: 1
 	Reload reason: initial
 	Finished: No
 	Packs: vanilla, fabric, file/Stay_True_1.20, file/NoBushyLeaves
 Stacktrace:
 	at net.minecraft.class_6360.method_36565(class_6360.java:49)
 	at net.minecraft.class_310.method_1587(class_310.java:2413)
 	at net.minecraft.class_310.method_1514(class_310.java:821)
 	at net.minecraft.client.main.Main.main(Main.java:250)
 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
 Mixins in Stacktrace:
 	net.minecraft.class_310:
 		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
 		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
 		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
 		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
 		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
 		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (dashloader.mixins.json)
 		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
 		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
 	net.minecraft.client.main.Main:
 		dev.notalpha.dashloader.mixin.main.MainMixin (dashloader.mixins.json)
```

**Comment by MagmaSlime123** [comment]
Huh. Not sure why Quilt thought it was Sodium when it is DL's fault.

**Comment by BuggyAl** [comment]
> Huh. Not sure why Quilt thought it was Sodium when it is DL's fault.

They must've skimmed your logs. It says it on line 132 💀 
`[16:52:19] [main/WARN]: @Mixin target net/minecraft/client/font/FontManager$1 was not found #dashloader:dashloader.mixins.json:option.cache.font.FontManagerOverride from mod dashloader`

**Comment by MagmaSlime123** [comment]
Ugh, another bouncy ball moment, lol. (Being told to go to another issue, then that issue being closed and being told to go somewhere else again.)

**Comment by alphaqu** [comment]
Hey! This is an incompatibility with sodium which is getting fixed in the next release. (Should be fixed at the end of this week)

**Comment by auyylaso** [comment]
It sure took me awhile to figure out the mixing traces but yes can confirm on all loads after the first one results in a crash due to the caching of Dashload.

**Comment by alphaqu** [comment]
Closing because there is #63
