### ISSUE TITLE
[LAUNCH]: Incompatibility with Fusion

### ISSUE THREAD

**Issue by Feliks-WR** [QuantumFusionMC/DashLoader-Definitions#85]
### Version

5.0.0-beta.2

### Minecraft Version

1.20.1

### Entire Logs

https://mclo.gs/h76X4ue

### Additional Notes

[15:09:48] [dashloader-thread/INFO]:
 Starting DashLoader Caching
dev.notalpha.dashloader.api.registry.RegistryAddException: Could not find a ChunkWriter for class com.supermartijn642.fusion.texture.types.connecting.ConnectingTextureSprite: TextureAtlasSprite{contents='SpriteContents{name=rechiseled:block/oak_planks_bricks, frameCount=1, height=128, width=128}', u0=0.9746094, u1=0.9765625, v0=0.1875, v1=0.19140625}
	at dev.notalpha.dashloader.registry.RegistryWriterImpl.addObject(RegistryWriterImpl.java:117) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.registry.RegistryWriterImpl.add(RegistryWriterImpl.java:68) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.client.sprite.DashStitchResult.lambda$new$0(DashStitchResult.java:39) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.client.sprite.DashStitchResult.<init>(DashStitchResult.java:38) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.client.sprite.SpriteModule.lambda$save$0(SpriteModule.java:36) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.client.sprite.SpriteModule.save(SpriteModule.java:33) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.client.sprite.SpriteModule.save(SpriteModule.java:18) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.io.MappingSerializer.save(MappingSerializer.java:48) ~[transformed-mod-dashloader.i0:0/:?]
	at dev.notalpha.dashloader.CacheImpl.save(CacheImpl.java:130) ~[transformed-mod-dashloader.i0:0/:?]
	at net.minecraft.class_425.md811124$dashloader$lambda$done$1$1(class_425.java:4076) ~[transformed-mod-minecraft.i0:0/:?]

**Comment by 5ur3z** [comment]
same on 1.21.1 fabric with continuity mod
